name: Simple Flask Application CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Docker Build
        run: docker build -t simple-503 .
      - name: Tags
        run: |
          docker tag simple-503 ${{ secrets.DOCKER_HUB_USER }}/simple-503:${{ github.sha }}
          docker tag simple-503 ${{ secrets.DOCKER_HUB_USER }}/simple-503:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_HUB_USER }}/simple-503:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USER }}/simple-503:latest